version: "3.8"

services:   
  mysql_db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - sentiment_app

  model_logreg_api:
    image: sentiment_pred_logreg
    build: ./model_logreg
    ports:
      - 5001:5000
    networks:
      - sentiment_app

networks:
  sentiment_app:
      


      